/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutPrieskaRouteImport } from './routes/about-prieska'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences/index'
import { Route as ExperiencesIdRouteImport } from './routes/experiences/$id'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedDashboardExperiencesRouteImport } from './routes/_authed/dashboard/experiences'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPrieskaRoute = AboutPrieskaRouteImport.update({
  id: '/about-prieska',
  path: '/about-prieska',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIdRoute = ExperiencesIdRouteImport.update({
  id: '/experiences/$id',
  path: '/experiences/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardExperiencesRoute =
  AuthedDashboardExperiencesRouteImport.update({
    id: '/dashboard/experiences',
    path: '/dashboard/experiences',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-prieska': typeof AboutPrieskaRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/heritage': typeof HeritageRoute
  '/login': typeof LoginRoute
  '/experiences/$id': typeof ExperiencesIdRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/dashboard/experiences': typeof AuthedDashboardExperiencesRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-prieska': typeof AboutPrieskaRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/heritage': typeof HeritageRoute
  '/login': typeof LoginRoute
  '/experiences/$id': typeof ExperiencesIdRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/dashboard/experiences': typeof AuthedDashboardExperiencesRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about-prieska': typeof AboutPrieskaRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/heritage': typeof HeritageRoute
  '/login': typeof LoginRoute
  '/experiences/$id': typeof ExperiencesIdRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/_authed/dashboard/experiences': typeof AuthedDashboardExperiencesRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-prieska'
    | '/contact'
    | '/gallery'
    | '/heritage'
    | '/login'
    | '/experiences/$id'
    | '/experiences/'
    | '/dashboard/experiences'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-prieska'
    | '/contact'
    | '/gallery'
    | '/heritage'
    | '/login'
    | '/experiences/$id'
    | '/experiences'
    | '/dashboard/experiences'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about-prieska'
    | '/contact'
    | '/gallery'
    | '/heritage'
    | '/login'
    | '/experiences/$id'
    | '/experiences/'
    | '/_authed/dashboard/experiences'
    | '/_authed/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutPrieskaRoute: typeof AboutPrieskaRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HeritageRoute: typeof HeritageRoute
  LoginRoute: typeof LoginRoute
  ExperiencesIdRoute: typeof ExperiencesIdRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-prieska': {
      id: '/about-prieska'
      path: '/about-prieska'
      fullPath: '/about-prieska'
      preLoaderRoute: typeof AboutPrieskaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$id': {
      id: '/experiences/$id'
      path: '/experiences/$id'
      fullPath: '/experiences/$id'
      preLoaderRoute: typeof ExperiencesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/experiences': {
      id: '/_authed/dashboard/experiences'
      path: '/dashboard/experiences'
      fullPath: '/dashboard/experiences'
      preLoaderRoute: typeof AuthedDashboardExperiencesRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardExperiencesRoute: typeof AuthedDashboardExperiencesRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardExperiencesRoute: AuthedDashboardExperiencesRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutPrieskaRoute: AboutPrieskaRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HeritageRoute: HeritageRoute,
  LoginRoute: LoginRoute,
  ExperiencesIdRoute: ExperiencesIdRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
